# Generated by Django 3.1.5 on 2021-06-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20210604_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
